modLoader = "javafml"
loaderVersion = "${neoforge_loader}"
license = "${license}"
issueTrackerURL="https://github.com/Ocelot5836/imguimc/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
logoFile = "${id}.png"
logoBlur = false
authors = "${author}"
description = '''${description}'''

[[mixins]]
config = "${id}.mixins.json"

[[dependencies.${id}]]
modId = "neoforge"
type="required"
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "axiom"
type = "incompatible"
reason = "ImGui implementation conflict"

[[dependencies.${id}]]
modId = "flashback"
type = "incompatible"
reason = "ImGui implementation conflict"

[[dependencies.${id}]]
modId = "veil"
type = "incompatible"
versionRange = "[,4.0.0)"
reason = "ImGui implementation conflict"
